name: "docker-publish"
description: "Builds and published docker image"

inputs:
  registry: 
    required: false
    description: "Docker registry for publishing"
    default: "ghcr.io"
  image_name: 
    required: false
    description: "Docker image name"
    default: ${{ github.repository }}
  tag:
    required: false
    description: "Tag to use for docker image"
    default: ${{ github.ref_name }}
  token:
    required: true
    description: "Github Access Token"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Convert image to lowercase 
      id: image_name_conversion
      shell: bash
      run: INPUT=${{ inputs.image_name }}; echo "image_name_lower=${INPUT,,}">>${GITHUB_OUTPUT}

    # Install the cosign tool except on PR
    # https://github.com/sigstore/cosign-installer
    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb #v3.8.2
      with:
        cosign-release: 'v2.2.4'

    # Set up BuildKit Docker container builder to be able to build
    # multi-platform images and export cache
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ inputs.registry }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
      with:
        images: ${{ inputs.registry }}/${{ steps.image_name_conversion.outputs.image_name_lower }}

    # Build and push Docker image with Buildx
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
      with:
        context: .
        push: true
        tags: ${{ inputs.registry }}/${{ steps.image_name_conversion.outputs.image_name_lower }}:${{ inputs.tag }},${{ inputs.registry }}/${{ steps.image_name_conversion.outputs.image_name_lower }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Sign the resulting Docker image digest except on PRs.
    # This will only write to the public Rekor transparency log when the Docker
    # repository is public to avoid leaking data.  If you would like to publish
    # transparency data even for private images, pass --force to cosign below.
    # https://github.com/sigstore/cosign
    - name: Sign the published Docker image
      shell: bash
      if: ${{ github.event_name != 'pull_request' }}
      env:
        # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
        TAGS: ${{ inputs.registry }}/${{ steps.image_name_conversion.outputs.image_name_lower }}:${{ inputs.tag }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      # This step uses the identity token to provision an ephemeral certificate
      # against the sigstore community Fulcio instance.
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

